### ISSUE TITLE
No release file

### ISSUE THREAD

**Issue by linuxgurugamer** [satoi8080/KSP-Spear-of-Longinus#1]
CKAN will work better if you make a release file, it's failing because it can't find a release

**Comment by satoi8080** [comment]
Hello, @linuxgurugamer
Excuse me, but what does the "release file" look like?
Did you mean a pull request of .netkan file to NETKAN?
If yes, I was already doing that and failed.
If no, I've looked around the CKAN wiki but didn't find a specific description of "release file"

**Comment by linuxgurugamer** [comment]
A zip file of the mod, put in into the Releases area of your github repo, here:
https://github.com/satoi8080/KSP-Spear-of-Longinus/releases

The Netkan is ok, but it has nothing to install.

**Comment by satoi8080** [comment]
I see, thanks a lot!
